(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite6 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	infrared6 - mode
	thermograph3 - mode
	infrared1 - mode
	infrared5 - mode
	infrared2 - mode
	spectrograph0 - mode
	thermograph4 - mode
	GroundStation6 - direction
	GroundStation5 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star3 - direction
	Star0 - direction
	GroundStation4 - direction
	Planet7 - direction
	Phenomenon8 - direction
	Star9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 infrared6)
	(calibration_target instrument0 Star3)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 infrared5)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 thermograph4)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument5 infrared6)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 infrared6)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared6)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 infrared5)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 Star3)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon10)
	(supports instrument9 infrared2)
	(supports instrument9 infrared1)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star3)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared5)
	(supports instrument13 thermograph3)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument14 thermograph4)
	(supports instrument14 infrared1)
	(supports instrument14 infrared5)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 spectrograph0)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation4)
	(supports instrument16 infrared1)
	(supports instrument16 thermograph3)
	(supports instrument16 infrared6)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 thermograph3)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared6)
	(calibration_target instrument17 GroundStation6)
	(supports instrument18 spectrograph0)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star0)
	(supports instrument19 infrared5)
	(supports instrument19 infrared1)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation6)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon12)
	(supports instrument20 infrared6)
	(supports instrument20 infrared1)
	(supports instrument20 infrared5)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared6)
	(supports instrument21 thermograph4)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 Star3)
	(supports instrument22 infrared6)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation1)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared2)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 thermograph3)
	(supports instrument24 thermograph4)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star3)
	(supports instrument25 infrared5)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 GroundStation2)
	(supports instrument26 infrared1)
	(calibration_target instrument26 GroundStation6)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument27 infrared6)
	(supports instrument27 spectrograph0)
	(supports instrument27 infrared5)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 GroundStation1)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 GroundStation2)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 thermograph4)
	(supports instrument29 thermograph3)
	(supports instrument29 infrared2)
	(calibration_target instrument29 Star3)
	(supports instrument30 infrared1)
	(calibration_target instrument30 GroundStation5)
	(supports instrument31 infrared2)
	(supports instrument31 infrared5)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 thermograph3)
	(calibration_target instrument32 GroundStation1)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument33 infrared5)
	(supports instrument33 infrared2)
	(supports instrument33 infrared1)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 Star0)
	(supports instrument34 infrared2)
	(supports instrument34 infrared5)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 Star3)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 Star3)
	(supports instrument36 thermograph4)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation4)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation1)
)
(:goal (and
	(have_image Planet7 infrared2)
	(have_image Planet7 infrared6)
	(have_image Phenomenon8 thermograph3)
	(have_image Phenomenon8 infrared1)
	(have_image Star9 thermograph3)
	(have_image Star9 infrared1)
	(have_image Phenomenon10 thermograph4)
	(have_image Phenomenon10 infrared6)
	(have_image Phenomenon11 infrared1)
	(have_image Phenomenon11 infrared6)
	(have_image Phenomenon12 infrared1)
	(have_image Phenomenon12 infrared6)
))

)
