(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite5 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite6 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	image6 - mode
	image3 - mode
	infrared1 - mode
	infrared0 - mode
	infrared4 - mode
	spectrograph7 - mode
	image5 - mode
	thermograph2 - mode
	Star0 - direction
	GroundStation2 - direction
	Star7 - direction
	Star6 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	GroundStation4 - direction
	Star8 - direction
	Planet9 - direction
	Star10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 spectrograph7)
	(calibration_target instrument0 Star7)
	(supports instrument1 image3)
	(supports instrument1 spectrograph7)
	(calibration_target instrument1 Star6)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 Star0)
	(supports instrument3 infrared0)
	(supports instrument3 spectrograph7)
	(supports instrument3 infrared4)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star1)
	(supports instrument4 infrared1)
	(supports instrument4 infrared0)
	(supports instrument4 image5)
	(calibration_target instrument4 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet15)
	(supports instrument5 infrared4)
	(calibration_target instrument5 Star1)
	(supports instrument6 image5)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star7)
	(supports instrument7 infrared4)
	(supports instrument7 spectrograph7)
	(calibration_target instrument7 Star6)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star0)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument9 spectrograph7)
	(supports instrument9 image6)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 image6)
	(calibration_target instrument10 Star6)
	(supports instrument11 thermograph2)
	(supports instrument11 spectrograph7)
	(supports instrument11 image3)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star0)
	(supports instrument12 image3)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star6)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument13 spectrograph7)
	(supports instrument13 image3)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star1)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 Star1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star0)
	(supports instrument16 image3)
	(supports instrument16 image6)
	(supports instrument16 spectrograph7)
	(calibration_target instrument16 Star7)
	(supports instrument17 infrared4)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star6)
	(supports instrument18 infrared0)
	(supports instrument18 image3)
	(supports instrument18 image6)
	(calibration_target instrument18 Star0)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star1)
	(supports instrument20 spectrograph7)
	(calibration_target instrument20 Star0)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument21 image6)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 Star6)
	(supports instrument22 spectrograph7)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 infrared0)
	(supports instrument23 image5)
	(supports instrument23 infrared4)
	(calibration_target instrument23 Star7)
	(supports instrument24 thermograph2)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 infrared1)
	(supports instrument25 infrared0)
	(calibration_target instrument25 Star6)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon11)
	(supports instrument26 image3)
	(supports instrument26 infrared4)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star7)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 image5)
	(supports instrument28 thermograph2)
	(supports instrument28 spectrograph7)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 Star7)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star12)
	(supports instrument29 image3)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared1)
	(calibration_target instrument30 Star1)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star7)
	(supports instrument32 spectrograph7)
	(supports instrument32 infrared1)
	(calibration_target instrument32 Star6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon11)
	(supports instrument33 infrared1)
	(calibration_target instrument33 GroundStation3)
	(supports instrument34 thermograph2)
	(supports instrument34 infrared0)
	(calibration_target instrument34 Star1)
	(supports instrument35 infrared4)
	(supports instrument35 infrared0)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 GroundStation5)
	(supports instrument36 thermograph2)
	(supports instrument36 image5)
	(supports instrument36 spectrograph7)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 GroundStation3)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
)
(:goal (and
	(have_image Star8 image5)
	(have_image Star8 thermograph2)
	(have_image Planet9 infrared4)
	(have_image Star10 image3)
	(have_image Phenomenon11 image5)
	(have_image Phenomenon11 thermograph2)
	(have_image Star12 image5)
	(have_image Phenomenon13 image6)
	(have_image Star14 image5)
	(have_image Planet15 image5)
	(have_image Planet15 image3)
))

)
