(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite4 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite5 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	satellite7 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	infrared5 - mode
	infrared6 - mode
	image7 - mode
	thermograph4 - mode
	thermograph3 - mode
	infrared1 - mode
	spectrograph0 - mode
	infrared2 - mode
	GroundStation2 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	Star4 - direction
	Star7 - direction
	Star6 - direction
	Star1 - direction
	GroundStation0 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Star10 - direction
	Star11 - direction
	Planet12 - direction
	Star13 - direction
	Planet14 - direction
	Phenomenon15 - direction
)
(:init
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 Star6)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 GroundStation2)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared5)
	(supports instrument3 infrared2)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 infrared2)
	(supports instrument4 infrared5)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star1)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet9)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 Star4)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph3)
	(supports instrument7 infrared5)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star6)
	(supports instrument8 thermograph3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 infrared1)
	(supports instrument9 image7)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star6)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 spectrograph0)
	(supports instrument11 image7)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star1)
	(supports instrument12 spectrograph0)
	(supports instrument12 thermograph3)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared6)
	(calibration_target instrument13 GroundStation5)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star13)
	(supports instrument14 infrared1)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 Star4)
	(supports instrument15 infrared5)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star7)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star6)
	(supports instrument17 thermograph4)
	(supports instrument17 image7)
	(calibration_target instrument17 Star7)
	(supports instrument18 image7)
	(supports instrument18 thermograph3)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 Star4)
	(supports instrument19 infrared5)
	(supports instrument19 thermograph3)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 Star4)
	(supports instrument20 infrared1)
	(supports instrument20 thermograph4)
	(supports instrument20 infrared6)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star1)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon8)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared6)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 GroundStation3)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared2)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 infrared5)
	(supports instrument25 spectrograph0)
	(supports instrument25 infrared6)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 GroundStation3)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star4)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star11)
	(supports instrument27 infrared6)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 Star6)
	(supports instrument28 spectrograph0)
	(supports instrument28 infrared5)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 GroundStation3)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 GroundStation5)
	(calibration_target instrument29 Star1)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star13)
	(supports instrument30 infrared1)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 Star6)
	(supports instrument31 infrared2)
	(supports instrument31 infrared5)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 GroundStation0)
	(calibration_target instrument31 Star7)
	(supports instrument32 infrared2)
	(calibration_target instrument32 Star1)
	(calibration_target instrument32 Star6)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star7)
	(supports instrument34 spectrograph0)
	(supports instrument34 image7)
	(supports instrument34 thermograph3)
	(calibration_target instrument34 GroundStation3)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star10)
	(supports instrument35 infrared1)
	(supports instrument35 infrared5)
	(supports instrument35 infrared2)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 GroundStation5)
	(on_board instrument35 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet14)
	(supports instrument36 thermograph4)
	(supports instrument36 infrared5)
	(calibration_target instrument36 Star7)
	(calibration_target instrument36 Star4)
	(supports instrument37 infrared1)
	(supports instrument37 infrared6)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star1)
	(calibration_target instrument37 Star6)
	(supports instrument38 image7)
	(supports instrument38 thermograph4)
	(supports instrument38 infrared2)
	(calibration_target instrument38 GroundStation0)
	(supports instrument39 image7)
	(supports instrument39 infrared2)
	(calibration_target instrument39 Star4)
	(calibration_target instrument39 GroundStation3)
	(supports instrument40 spectrograph0)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 Star6)
	(calibration_target instrument40 Star1)
	(supports instrument41 thermograph3)
	(calibration_target instrument41 Star6)
	(calibration_target instrument41 Star7)
	(supports instrument42 infrared2)
	(supports instrument42 spectrograph0)
	(supports instrument42 infrared1)
	(calibration_target instrument42 GroundStation0)
	(calibration_target instrument42 Star1)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet14)
)
(:goal (and
	(have_image Phenomenon8 spectrograph0)
	(have_image Planet9 infrared2)
	(have_image Star10 infrared1)
	(have_image Planet12 infrared2)
	(have_image Star13 infrared5)
	(have_image Planet14 infrared1)
	(have_image Planet14 spectrograph0)
	(have_image Phenomenon15 thermograph3)
	(have_image Phenomenon15 image7)
))

)
