(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite3 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite4 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite5 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite6 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite7 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	thermograph3 - mode
	spectrograph5 - mode
	infrared4 - mode
	infrared0 - mode
	thermograph7 - mode
	infrared2 - mode
	thermograph1 - mode
	image6 - mode
	GroundStation4 - direction
	Star2 - direction
	Star1 - direction
	GroundStation7 - direction
	Star3 - direction
	Star6 - direction
	Star0 - direction
	GroundStation5 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
	Planet12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 image6)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph3)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph1)
	(supports instrument2 thermograph3)
	(supports instrument2 thermograph7)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph3)
	(supports instrument3 infrared2)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 Star6)
	(supports instrument4 spectrograph5)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star6)
	(supports instrument5 infrared4)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star6)
	(supports instrument6 infrared4)
	(calibration_target instrument6 Star3)
	(supports instrument7 thermograph3)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(supports instrument8 spectrograph5)
	(calibration_target instrument8 GroundStation7)
	(supports instrument9 thermograph7)
	(supports instrument9 spectrograph5)
	(calibration_target instrument9 Star6)
	(supports instrument10 infrared0)
	(supports instrument10 image6)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star2)
	(supports instrument11 spectrograph5)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star3)
	(supports instrument12 image6)
	(supports instrument12 thermograph3)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star6)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph7)
	(supports instrument13 infrared0)
	(calibration_target instrument13 Star2)
	(supports instrument14 thermograph7)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 thermograph1)
	(supports instrument15 infrared0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star6)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument16 image6)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 Star2)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 spectrograph5)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star2)
	(supports instrument19 infrared4)
	(supports instrument19 thermograph7)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 spectrograph5)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 infrared0)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star0)
	(supports instrument22 infrared0)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star3)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet8)
	(supports instrument23 infrared4)
	(supports instrument23 thermograph1)
	(supports instrument23 infrared2)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star1)
	(supports instrument24 infrared4)
	(supports instrument24 image6)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 Star2)
	(supports instrument25 thermograph7)
	(supports instrument25 infrared4)
	(supports instrument25 image6)
	(calibration_target instrument25 Star6)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star6)
	(supports instrument27 infrared4)
	(calibration_target instrument27 GroundStation5)
	(supports instrument28 infrared4)
	(supports instrument28 infrared0)
	(supports instrument28 infrared2)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 Star0)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet15)
	(supports instrument29 spectrograph5)
	(supports instrument29 thermograph3)
	(supports instrument29 infrared4)
	(calibration_target instrument29 Star2)
	(calibration_target instrument29 GroundStation7)
	(supports instrument30 image6)
	(supports instrument30 thermograph7)
	(supports instrument30 infrared2)
	(calibration_target instrument30 GroundStation5)
	(supports instrument31 spectrograph5)
	(calibration_target instrument31 Star3)
	(supports instrument32 image6)
	(supports instrument32 thermograph3)
	(calibration_target instrument32 GroundStation7)
	(supports instrument33 infrared4)
	(calibration_target instrument33 Star1)
	(supports instrument34 infrared0)
	(calibration_target instrument34 GroundStation7)
	(calibration_target instrument34 Star3)
	(supports instrument35 image6)
	(calibration_target instrument35 Star0)
	(supports instrument36 image6)
	(supports instrument36 thermograph1)
	(calibration_target instrument36 Star1)
	(calibration_target instrument36 GroundStation5)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon13)
	(supports instrument37 infrared4)
	(supports instrument37 infrared0)
	(calibration_target instrument37 Star0)
	(supports instrument38 thermograph3)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 Star3)
	(supports instrument39 infrared2)
	(supports instrument39 infrared0)
	(calibration_target instrument39 Star6)
	(calibration_target instrument39 Star3)
	(supports instrument40 spectrograph5)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 thermograph7)
	(supports instrument41 thermograph3)
	(supports instrument41 image6)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star3)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument42 infrared0)
	(supports instrument42 infrared4)
	(supports instrument42 image6)
	(calibration_target instrument42 GroundStation7)
	(supports instrument43 spectrograph5)
	(calibration_target instrument43 GroundStation7)
	(supports instrument44 thermograph7)
	(supports instrument44 infrared4)
	(supports instrument44 infrared0)
	(calibration_target instrument44 Star0)
	(supports instrument45 infrared2)
	(calibration_target instrument45 Star3)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 thermograph1)
	(supports instrument46 infrared0)
	(calibration_target instrument46 GroundStation7)
	(calibration_target instrument46 Star1)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon14)
	(supports instrument47 thermograph1)
	(supports instrument47 image6)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 GroundStation7)
	(supports instrument48 infrared2)
	(supports instrument48 thermograph1)
	(supports instrument48 thermograph7)
	(calibration_target instrument48 Star6)
	(supports instrument49 image6)
	(supports instrument49 thermograph1)
	(calibration_target instrument49 GroundStation5)
	(calibration_target instrument49 Star0)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet12)
)
(:goal (and
	(have_image Planet8 thermograph7)
	(have_image Planet9 infrared0)
	(have_image Phenomenon10 image6)
	(have_image Phenomenon10 spectrograph5)
	(have_image Phenomenon11 spectrograph5)
	(have_image Phenomenon11 image6)
	(have_image Planet12 image6)
	(have_image Planet12 thermograph7)
	(have_image Phenomenon13 infrared0)
	(have_image Phenomenon14 infrared2)
	(have_image Planet15 spectrograph5)
))

)
