(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	infrared0 - mode
	image5 - mode
	infrared4 - mode
	image3 - mode
	thermograph2 - mode
	infrared1 - mode
	GroundStation5 - direction
	GroundStation1 - direction
	Star3 - direction
	GroundStation4 - direction
	Star0 - direction
	GroundStation2 - direction
	Star6 - direction
	Phenomenon7 - direction
	Planet8 - direction
	Star9 - direction
	Star10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared0)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument2 image3)
	(supports instrument2 infrared1)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 infrared1)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared0)
	(supports instrument4 infrared4)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation5)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon11)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 image3)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 infrared0)
	(supports instrument8 infrared4)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star10)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 thermograph2)
	(supports instrument10 infrared0)
	(supports instrument10 image5)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 image5)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 thermograph2)
	(supports instrument12 infrared4)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 infrared4)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 GroundStation5)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument14 infrared0)
	(supports instrument14 infrared4)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 infrared4)
	(supports instrument15 image5)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star10)
	(supports instrument16 thermograph2)
	(supports instrument16 infrared1)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 infrared4)
	(supports instrument17 infrared1)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star3)
	(supports instrument19 infrared1)
	(supports instrument19 thermograph2)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star0)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon11)
)
(:goal (and
	(have_image Star6 infrared0)
	(have_image Phenomenon7 infrared1)
	(have_image Planet8 image5)
	(have_image Star9 thermograph2)
	(have_image Star9 infrared4)
	(have_image Star10 infrared1)
	(have_image Phenomenon11 thermograph2)
))

)
