(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	spectrograph5 - mode
	spectrograph0 - mode
	image3 - mode
	thermograph4 - mode
	image1 - mode
	infrared2 - mode
	Star1 - direction
	Star3 - direction
	Star2 - direction
	GroundStation5 - direction
	Star4 - direction
	Star0 - direction
	Star6 - direction
	Planet7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star2)
	(supports instrument1 spectrograph5)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star4)
	(supports instrument2 spectrograph5)
	(supports instrument2 spectrograph0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star2)
	(supports instrument3 image3)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 Star4)
	(supports instrument4 image1)
	(supports instrument4 spectrograph5)
	(supports instrument4 image3)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet7)
	(supports instrument5 infrared2)
	(supports instrument5 image1)
	(supports instrument5 image3)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star1)
	(supports instrument7 image3)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star0)
	(supports instrument8 image1)
	(supports instrument8 spectrograph0)
	(supports instrument8 infrared2)
	(calibration_target instrument8 Star3)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 Star1)
	(supports instrument10 infrared2)
	(supports instrument10 image3)
	(supports instrument10 image1)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation5)
	(supports instrument12 spectrograph0)
	(supports instrument12 image1)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star1)
	(supports instrument13 spectrograph5)
	(supports instrument13 infrared2)
	(supports instrument13 image1)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star3)
	(supports instrument14 spectrograph5)
	(supports instrument14 image1)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation5)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument15 thermograph4)
	(supports instrument15 image3)
	(calibration_target instrument15 Star3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument16 image1)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph5)
	(calibration_target instrument16 Star3)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument18 image3)
	(supports instrument18 spectrograph0)
	(supports instrument18 image1)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star4)
	(supports instrument19 image1)
	(supports instrument19 thermograph4)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star2)
	(supports instrument20 infrared2)
	(supports instrument20 image1)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 Star4)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
)
(:goal (and
	(have_image Star6 thermograph4)
	(have_image Star6 spectrograph5)
	(have_image Planet7 image1)
	(have_image Planet7 spectrograph0)
	(have_image Planet9 image3)
	(have_image Planet9 spectrograph0)
	(have_image Phenomenon10 image1)
	(have_image Star11 image3)
	(have_image Star11 spectrograph5)
))

)
