(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	image5 - mode
	spectrograph4 - mode
	spectrograph2 - mode
	spectrograph1 - mode
	image3 - mode
	infrared0 - mode
	GroundStation0 - direction
	Star3 - direction
	Star4 - direction
	GroundStation5 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Star10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 spectrograph4)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star3)
	(supports instrument1 infrared0)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 spectrograph4)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star4)
	(supports instrument5 spectrograph2)
	(supports instrument5 spectrograph1)
	(supports instrument5 image3)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star4)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument6 spectrograph1)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star3)
	(supports instrument7 spectrograph2)
	(supports instrument7 spectrograph1)
	(supports instrument7 image3)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 spectrograph1)
	(supports instrument8 spectrograph4)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 GroundStation5)
	(supports instrument9 infrared0)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star3)
	(supports instrument10 spectrograph4)
	(supports instrument10 image3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star3)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon8)
	(supports instrument12 infrared0)
	(supports instrument12 spectrograph4)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 infrared0)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument14 spectrograph4)
	(supports instrument14 infrared0)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 Star4)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 Star3)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet9)
	(supports instrument16 spectrograph1)
	(supports instrument16 infrared0)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 spectrograph1)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 infrared0)
	(supports instrument18 spectrograph4)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 Star4)
	(supports instrument19 spectrograph2)
	(supports instrument19 infrared0)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 infrared0)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation2)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon7)
)
(:goal (and
	(have_image Star6 spectrograph1)
	(have_image Phenomenon7 spectrograph4)
	(have_image Phenomenon7 infrared0)
	(have_image Planet9 infrared0)
	(have_image Star10 spectrograph4)
	(have_image Star11 infrared0)
))

)
