(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	infrared4 - mode
	image0 - mode
	infrared3 - mode
	infrared5 - mode
	thermograph2 - mode
	infrared1 - mode
	Star2 - direction
	Star3 - direction
	Star4 - direction
	GroundStation5 - direction
	Star0 - direction
	GroundStation1 - direction
	Phenomenon6 - direction
	Star7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared5)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star4)
	(supports instrument1 thermograph2)
	(supports instrument1 infrared3)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument2 thermograph2)
	(supports instrument2 infrared5)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 thermograph2)
	(supports instrument3 infrared4)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet9)
	(supports instrument5 infrared5)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 infrared5)
	(calibration_target instrument6 GroundStation5)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared3)
	(supports instrument7 infrared5)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared1)
	(supports instrument8 infrared4)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 Star3)
	(supports instrument9 image0)
	(supports instrument9 infrared1)
	(supports instrument9 infrared5)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star4)
	(supports instrument10 infrared5)
	(supports instrument10 infrared4)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument11 infrared4)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared5)
	(supports instrument12 thermograph2)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation5)
	(supports instrument13 thermograph2)
	(supports instrument13 infrared5)
	(calibration_target instrument13 Star3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument14 thermograph2)
	(supports instrument14 infrared5)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star4)
	(supports instrument16 infrared4)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 GroundStation1)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet8)
	(supports instrument17 infrared3)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star3)
	(supports instrument18 infrared5)
	(supports instrument18 image0)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star4)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 thermograph2)
	(supports instrument20 infrared5)
	(supports instrument20 infrared3)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation1)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon6)
)
(:goal (and
	(have_image Phenomenon6 infrared3)
	(have_image Phenomenon6 thermograph2)
	(have_image Planet8 image0)
	(have_image Planet9 thermograph2)
	(have_image Planet9 infrared5)
	(have_image Phenomenon10 infrared1)
	(have_image Phenomenon10 image0)
	(have_image Star11 infrared5)
))

)
