(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	spectrograph1 - mode
	thermograph4 - mode
	image2 - mode
	thermograph0 - mode
	spectrograph3 - mode
	image5 - mode
	GroundStation3 - direction
	Star5 - direction
	Star0 - direction
	Star1 - direction
	Star2 - direction
	Star4 - direction
	Planet6 - direction
	Planet7 - direction
	Planet8 - direction
	Star9 - direction
	Star10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 Star5)
	(supports instrument1 image5)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star1)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 Star0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument4 spectrograph1)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 Star0)
	(supports instrument5 image5)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph4)
	(supports instrument6 spectrograph3)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation3)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet6)
	(supports instrument7 image5)
	(supports instrument7 thermograph0)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star5)
	(supports instrument8 image2)
	(calibration_target instrument8 Star1)
	(supports instrument9 thermograph4)
	(supports instrument9 thermograph0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star1)
	(supports instrument10 image2)
	(calibration_target instrument10 Star0)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star11)
	(supports instrument11 image5)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 GroundStation3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet7)
	(supports instrument12 image2)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star4)
	(supports instrument13 thermograph0)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star1)
	(supports instrument14 thermograph4)
	(supports instrument14 image5)
	(supports instrument14 spectrograph3)
	(calibration_target instrument14 Star1)
	(supports instrument15 spectrograph3)
	(supports instrument15 image2)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 Star4)
	(supports instrument16 thermograph0)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 Star1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation3)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument18 image5)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star0)
	(supports instrument19 image2)
	(supports instrument19 spectrograph3)
	(calibration_target instrument19 Star4)
	(calibration_target instrument19 Star0)
	(supports instrument20 image2)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star2)
	(supports instrument21 image2)
	(calibration_target instrument21 Star1)
	(supports instrument22 thermograph0)
	(supports instrument22 image2)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 Star1)
	(supports instrument23 image5)
	(supports instrument23 spectrograph3)
	(calibration_target instrument23 Star4)
	(calibration_target instrument23 Star2)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet6)
)
(:goal (and
	(have_image Planet6 thermograph4)
	(have_image Planet7 thermograph4)
	(have_image Planet7 spectrograph3)
	(have_image Planet8 image2)
	(have_image Star9 spectrograph1)
	(have_image Star10 spectrograph3)
	(have_image Star10 thermograph0)
	(have_image Star11 spectrograph3)
))

)
