(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	image5 - mode
	spectrograph0 - mode
	thermograph1 - mode
	image3 - mode
	image4 - mode
	thermograph2 - mode
	GroundStation1 - direction
	GroundStation2 - direction
	Star0 - direction
	Star3 - direction
	Star4 - direction
	Star5 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 image4)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star4)
	(supports instrument1 thermograph1)
	(supports instrument1 image5)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 Star0)
	(supports instrument2 image4)
	(supports instrument2 thermograph2)
	(supports instrument2 image3)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 thermograph1)
	(supports instrument3 image5)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star3)
	(supports instrument4 image5)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon9)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 Star5)
	(supports instrument7 image4)
	(calibration_target instrument7 Star4)
	(supports instrument8 image4)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 Star4)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 thermograph2)
	(supports instrument10 image5)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star4)
	(supports instrument11 image5)
	(supports instrument11 thermograph1)
	(supports instrument11 image4)
	(calibration_target instrument11 Star4)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star4)
	(supports instrument12 thermograph2)
	(supports instrument12 image5)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 Star0)
	(supports instrument14 image3)
	(calibration_target instrument14 Star3)
	(supports instrument15 image3)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 Star5)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(supports instrument16 image3)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star3)
	(supports instrument17 spectrograph0)
	(supports instrument17 image4)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 Star0)
	(supports instrument18 image4)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star4)
	(supports instrument19 image3)
	(calibration_target instrument19 Star0)
	(supports instrument20 image4)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star4)
	(supports instrument21 image3)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 Star4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon7)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 Star4)
	(calibration_target instrument22 Star5)
	(supports instrument23 image4)
	(calibration_target instrument23 Star4)
	(supports instrument24 thermograph2)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star4)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
)
(:goal (and
	(have_image Phenomenon6 spectrograph0)
	(have_image Phenomenon7 thermograph2)
	(have_image Phenomenon7 image3)
	(have_image Phenomenon8 image3)
	(have_image Planet10 image4)
	(have_image Planet10 spectrograph0)
	(have_image Star11 image3)
	(have_image Star11 thermograph2)
))

)
