(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	thermograph0 - mode
	image4 - mode
	spectrograph5 - mode
	image3 - mode
	image2 - mode
	infrared1 - mode
	GroundStation0 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	Star3 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Planet9 - direction
	Planet10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 spectrograph5)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 image4)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star3)
	(supports instrument2 image3)
	(supports instrument2 spectrograph5)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet10)
	(supports instrument3 thermograph0)
	(supports instrument3 infrared1)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 infrared1)
	(supports instrument4 image4)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star3)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star3)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 GroundStation5)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument7 image3)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 spectrograph5)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 Star3)
	(supports instrument9 spectrograph5)
	(supports instrument9 image3)
	(calibration_target instrument9 Star3)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument10 image4)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph0)
	(supports instrument11 spectrograph5)
	(supports instrument11 image2)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 infrared1)
	(supports instrument12 spectrograph5)
	(supports instrument12 image2)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation5)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument13 infrared1)
	(supports instrument13 image3)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 image3)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 thermograph0)
	(supports instrument15 infrared1)
	(supports instrument15 spectrograph5)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 thermograph0)
	(supports instrument16 spectrograph5)
	(supports instrument16 image2)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 image3)
	(supports instrument17 infrared1)
	(supports instrument17 image4)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 thermograph0)
	(supports instrument18 image2)
	(calibration_target instrument18 GroundStation5)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star8)
	(supports instrument19 infrared1)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 infrared1)
	(supports instrument20 image4)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 spectrograph5)
	(supports instrument21 image2)
	(calibration_target instrument21 Star3)
	(supports instrument22 spectrograph5)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star3)
	(supports instrument23 image2)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star3)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet9)
)
(:goal (and
	(have_image Phenomenon6 image4)
	(have_image Phenomenon7 image2)
	(have_image Phenomenon7 image3)
	(have_image Star8 image2)
	(have_image Star8 infrared1)
	(have_image Planet9 image3)
	(have_image Planet10 thermograph0)
	(have_image Star11 image4)
))

)
