(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite2 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite3 - satellite
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	satellite6 - satellite
	instrument21 - instrument
	instrument22 - instrument
	spectrograph1 - mode
	image2 - mode
	image0 - mode
	image4 - mode
	spectrograph3 - mode
	image5 - mode
	thermograph6 - mode
	GroundStation6 - direction
	Star1 - direction
	GroundStation4 - direction
	Star2 - direction
	GroundStation0 - direction
	GroundStation3 - direction
	GroundStation5 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Planet10 - direction
	Planet11 - direction
	Planet12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 image2)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 Star2)
	(supports instrument2 image0)
	(calibration_target instrument2 Star2)
	(supports instrument3 spectrograph3)
	(supports instrument3 image4)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 GroundStation6)
	(supports instrument4 thermograph6)
	(supports instrument4 spectrograph1)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 Star1)
	(supports instrument5 image5)
	(supports instrument5 thermograph6)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 spectrograph3)
	(calibration_target instrument6 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet10)
	(supports instrument7 image4)
	(supports instrument7 image0)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 Star1)
	(supports instrument8 image5)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 image0)
	(supports instrument9 image2)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 image2)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 image2)
	(calibration_target instrument11 Star2)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument12 spectrograph3)
	(calibration_target instrument12 GroundStation6)
	(supports instrument13 image5)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation6)
	(supports instrument14 image4)
	(supports instrument14 image5)
	(supports instrument14 spectrograph3)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 image0)
	(supports instrument15 spectrograph3)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 GroundStation3)
	(calibration_target instrument15 GroundStation0)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation4)
	(supports instrument16 image2)
	(supports instrument16 image4)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation3)
	(supports instrument17 image4)
	(supports instrument17 image2)
	(supports instrument17 image5)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star1)
	(supports instrument18 spectrograph1)
	(supports instrument18 image2)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 image2)
	(supports instrument19 image0)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 GroundStation0)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet13)
	(supports instrument20 image0)
	(supports instrument20 image2)
	(calibration_target instrument20 Star2)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet11)
	(supports instrument21 image5)
	(supports instrument21 spectrograph3)
	(supports instrument21 image4)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 thermograph6)
	(supports instrument22 image5)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation3)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon8)
)
(:goal (and
	(have_image Phenomenon7 spectrograph1)
	(have_image Phenomenon7 image2)
	(have_image Phenomenon8 thermograph6)
	(have_image Planet9 image4)
	(have_image Planet9 image2)
	(have_image Planet10 image5)
	(have_image Planet10 image0)
	(have_image Planet11 image5)
	(have_image Planet11 image4)
	(have_image Planet12 spectrograph1)
	(have_image Planet13 spectrograph1)
	(have_image Planet13 thermograph6)
))

)
