(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite6 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	image1 - mode
	spectrograph2 - mode
	infrared0 - mode
	spectrograph6 - mode
	infrared4 - mode
	image3 - mode
	image5 - mode
	Star1 - direction
	Star6 - direction
	GroundStation2 - direction
	Star3 - direction
	GroundStation4 - direction
	Star5 - direction
	GroundStation0 - direction
	Planet7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 image1)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet13)
	(supports instrument2 spectrograph6)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 spectrograph6)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation2)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 infrared0)
	(supports instrument5 image3)
	(calibration_target instrument5 Star5)
	(supports instrument6 image3)
	(supports instrument6 image1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet7)
	(supports instrument7 image5)
	(supports instrument7 spectrograph6)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star5)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star3)
	(supports instrument9 infrared4)
	(supports instrument9 image5)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 spectrograph2)
	(supports instrument10 image5)
	(calibration_target instrument10 Star3)
	(supports instrument11 image3)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 image1)
	(supports instrument12 infrared4)
	(supports instrument12 spectrograph6)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet7)
	(supports instrument13 image3)
	(supports instrument13 spectrograph6)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation4)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 image1)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation4)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation0)
	(calibration_target instrument16 Star6)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star8)
	(supports instrument17 infrared4)
	(supports instrument17 spectrograph6)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star6)
	(supports instrument18 spectrograph2)
	(supports instrument18 spectrograph6)
	(supports instrument18 image3)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star6)
	(supports instrument19 image5)
	(supports instrument19 image1)
	(supports instrument19 infrared4)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 Star6)
	(supports instrument20 image1)
	(supports instrument20 infrared4)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation0)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 GroundStation2)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 infrared0)
	(supports instrument22 infrared4)
	(calibration_target instrument22 Star3)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon12)
	(supports instrument23 spectrograph6)
	(supports instrument23 image5)
	(supports instrument23 infrared4)
	(calibration_target instrument23 GroundStation0)
	(calibration_target instrument23 Star5)
	(supports instrument24 image3)
	(supports instrument24 infrared4)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 GroundStation4)
	(supports instrument25 image5)
	(calibration_target instrument25 GroundStation0)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star1)
)
(:goal (and
	(have_image Star8 infrared0)
	(have_image Star8 spectrograph6)
	(have_image Phenomenon9 image3)
	(have_image Phenomenon9 image5)
	(have_image Planet10 image1)
	(have_image Planet10 spectrograph6)
	(have_image Star11 spectrograph2)
	(have_image Star11 image1)
	(have_image Phenomenon12 image5)
	(have_image Planet13 spectrograph6)
))

)
