(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite5 - satellite
	instrument20 - instrument
	satellite6 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite7 - satellite
	instrument26 - instrument
	instrument27 - instrument
	image5 - mode
	spectrograph3 - mode
	infrared7 - mode
	thermograph4 - mode
	image2 - mode
	thermograph0 - mode
	spectrograph1 - mode
	image6 - mode
	Star5 - direction
	Star3 - direction
	Star1 - direction
	GroundStation2 - direction
	GroundStation0 - direction
	Star4 - direction
	Star6 - direction
	GroundStation7 - direction
	Phenomenon8 - direction
	Star9 - direction
	Star10 - direction
	Star11 - direction
	Star12 - direction
	Planet13 - direction
	Phenomenon14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 Star1)
	(supports instrument1 spectrograph3)
	(supports instrument1 image6)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star3)
	(supports instrument2 infrared7)
	(supports instrument2 image2)
	(supports instrument2 image5)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star3)
	(supports instrument3 infrared7)
	(supports instrument3 image6)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star9)
	(supports instrument4 image5)
	(supports instrument4 spectrograph3)
	(supports instrument4 infrared7)
	(calibration_target instrument4 GroundStation7)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument5 infrared7)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 Star4)
	(supports instrument6 image2)
	(supports instrument6 image5)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 image2)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation7)
	(supports instrument8 infrared7)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 Star5)
	(supports instrument9 spectrograph1)
	(supports instrument9 infrared7)
	(calibration_target instrument9 Star3)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 Star1)
	(supports instrument11 image2)
	(supports instrument11 infrared7)
	(supports instrument11 image6)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 infrared7)
	(supports instrument14 spectrograph1)
	(supports instrument14 image6)
	(calibration_target instrument14 Star5)
	(supports instrument15 spectrograph3)
	(supports instrument15 spectrograph1)
	(supports instrument15 image6)
	(calibration_target instrument15 GroundStation7)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument16 image2)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 Star3)
	(supports instrument17 image5)
	(supports instrument17 image6)
	(calibration_target instrument17 Star4)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 Star4)
	(supports instrument19 image2)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 GroundStation7)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon8)
	(supports instrument20 image6)
	(supports instrument20 thermograph0)
	(supports instrument20 image2)
	(calibration_target instrument20 GroundStation0)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument21 image5)
	(supports instrument21 image6)
	(calibration_target instrument21 Star1)
	(supports instrument22 image5)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star1)
	(supports instrument23 spectrograph3)
	(supports instrument23 image5)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation0)
	(supports instrument24 thermograph4)
	(supports instrument24 infrared7)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 thermograph0)
	(supports instrument25 image2)
	(calibration_target instrument25 GroundStation7)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation0)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 Star4)
	(supports instrument27 image6)
	(calibration_target instrument27 GroundStation7)
	(calibration_target instrument27 Star6)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star15)
)
(:goal (and
	(have_image Phenomenon8 thermograph0)
	(have_image Phenomenon8 spectrograph3)
	(have_image Star9 image2)
	(have_image Star9 infrared7)
	(have_image Star10 thermograph0)
	(have_image Star11 infrared7)
	(have_image Star12 image5)
	(have_image Star12 infrared7)
	(have_image Planet13 spectrograph3)
	(have_image Phenomenon14 image6)
	(have_image Phenomenon14 infrared7)
	(have_image Star15 thermograph0)
	(have_image Star15 infrared7)
))

)
